-- SELECT
-- 		t0.*, t7.BankID,BankAccountNo,BankProvince,BankCity,BankBranch,ReferenceNo,DPStatus,WDStatus,MemberBankAccountID,MemberBankAccountStatus, t7.BankName, t7.BankAccountMemberRemarks, t7.VerificationStatus, t7.OTPStatus
-- 	FROM dbo.fn_tbl_Member() t0
-- 	LEFT JOIN
-- 	(
-- 		SELECT t1.BankID,BankAccountNo,BankProvince,BankCity,BankBranch,ReferenceNo,DPStatus,WDStatus,MemberBankAccountID,MemberBankAccountStatus, t6.BankName, t1.AccountID, t1.Remarks as BankAccountMemberRemarks, t1.VerificationStatus, t1.OTPStatus
-- 		FROM dbo.BankAccountMember t1 
-- 		LEFT JOIN dbo.Bank t6 ON t6.BankID = t1.BankID
-- 	)
-- 	t7 ON t0.AccountID = t7.AccountID
-- 	WHERE t7.MemberBankAccountID = 1259

